#!/bin/zsh
CWAPPDIR=$(dirname "$0")
source $CWAPPDIR/var.sh
source $CWAPPDIR/install/main.sh
source $CWAPPDIR/init/main.sh

if [ $1 = "init" ]
  then
    init $2
  elif [ $1 = "install" ]
    then
      install
  elif [ $1 = "start" ]
    then
      wp server --host=`conf server.host` --port=`conf server.port`
  elif [ $1 = "-h" ]
    then
      cat $CWAPPDIR/help.md
  else
    echo "merci d'entrer une commande"
  fi
