#!/bin/zsh
CONFIGDIR=$(dirname "$0")/config
source $CONFIGDIR/variables.sh
source $CONFIGDIR/downloadWP.sh
source $CONFIGDIR/serveurIndex.sh
source $CONFIGDIR/createDatabase.sh
source $CONFIGDIR/installWP.sh
source $CONFIGDIR/installPlugins.sh
source $CONFIGDIR/createTheme.sh

if [ $1 ]
  then
    echo "Création du wordpress $projectname dans le dossier $dossierLocal / $projectname"
    downloadWP
    echo "Create Config File & Create DB"
    databaseCreate
    createLinkOrFile
    echo "Create InstallWP"
    installWP
    installPlugins
    createTheme
    $navigateur --new-window $serveur:$port/lv1_index.php &
  else
    echo "Veuillez entre le nom du projet (sans espace)"
  fi